backend:
  name: github_api
  repo: BitBalloon/middleman-homepage
  branch: master

collections:
  - name: "posts"
    label: "Blog Post"
    create: true
    folder: "source/blog"
    sort: "title:asc"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2", class: "entry-title text-center"}
      - {label: "Author", name: "author", widget: "string", tagname: "p", class: "entry-meta"}
      - {label: "Description", name: "description", widget: "string", tagname: "p"}
      - {label: "Tags", name: "tags", widget: "tags"}
      - {label: "Image", name: "image", widget: "image", folder: "images/posts"}
      - {label: "Post Body", name: "body", widget: "markdown"}
      - {label: "Published", name: "published", widget: "checkbox", default: true}
  - name: "docs"
    label: "Doc Page"
    create: true
    folder: "source/docs"
    fields:
      - {name: "layout", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "Title", name: "title", widget: "string", optional: false}
      - {label: "Position", name: "position", widget: "string", optional: false}
